FROM oven/bun:slim
WORKDIR /dklb
COPY package.json .
COPY ./server ./server
COPY ./tools/eslint ./tools/eslint
COPY ./tools/typescript ./tools/typescript

RUN bun i --production

EXPOSE 3000-3000
ENTRYPOINT ["bun", "run", "--cwd", "server", "start"]
