FROM oven/bun:slim
WORKDIR /dklb

COPY ./server ./

RUN sed -i '/"@dklb\/eslint-config": "workspace:\^"/d' ./package.json && \
    sed -i '/"@dklb\/tsconfig": "workspace:\^"/d' ./package.json

RUN bun install --production --ignore-scripts

EXPOSE 3000
ENTRYPOINT ["bun", "run", "start"]
