services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - '3000:3000'

  apps:
    build:
      context: .
      dockerfile: Dockerfile.apps
    ports:
      - '8000-8002:8000-8002'
    depends_on:
      - server
