/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EurojackpotNumbers: typeof import('./src/components/EurojackpotNumbers.vue')['default']
    GluecksSpiraleNumbers: typeof import('./src/components/GluecksSpiraleNumbers.vue')['default']
    IconEurojackpotDot: typeof import('./src/components/icons/IconEurojackpotDot.vue')['default']
    IconGluecksSpiraleMono: typeof import('./src/components/icons/IconGluecksSpiraleMono.vue')['default']
    IconKenoWhite: typeof import('./src/components/icons/IconKenoWhite.vue')['default']
    IconLotto6aus49: typeof import('./src/components/icons/IconLotto6aus49.vue')['default']
    IconToto: typeof import('./src/components/icons/IconToto.vue')['default']
    KenoNumbers: typeof import('./src/components/KenoNumbers.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LottoNumbers: typeof import('./src/components/LottoNumbers.vue')['default']
    MdiChevronRight: typeof import('~icons/mdi/chevron-right')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TotoNumbers: typeof import('./src/components/TotoNumbers.vue')['default']
  }
}
