/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MdiClose: typeof import('~icons/mdi/close')['default']
    MdiMenuDown: typeof import('~icons/mdi/menu-down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiButton: typeof import('./src/UiButton/UiButton.vue')['default']
    UiDialog: typeof import('./src/UiDialog/UiDialog.vue')['default']
    UiSelect: typeof import('./src/UiSelect/UiSelect.vue')['default']
    UiSeparator: typeof import('./src/UiSeparator/UiSeparator.vue')['default']
  }
}
