name: deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN }}

      - name: Deploy to Droplet
        run: |
          doctl compute ssh root@209.38.249.17 --ssh-command "
            cd /DKLB
            git pull origin main
            docker compose down
            docker compose up --build -d
          "
