name: e2e

on:
  push:
    branches:
      - main

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: /usr/lib/playwright

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install && bun add -D @playwright/test

      - name: Setup Docker
        run: bun run prepare:docker

      - name: Build Docker images
        run: docker compose build

      - name: Run Docker
        run: docker compose up -d

      - name: Install Playwright
        run: bunx playwright install --with-deps

      - name: Wait for Docker
        run: |
          until curl -s http://localhost:8000; do
            echo "Waiting for service..."
            sleep 1
          done

      - name: Test
        run: bun run --cwd playwright test
        env:
          HOME: /root

      # - uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 7

      - name: Stop Docker
        run: docker compose down
