name: e2e

on:
  push:
    branches:
      - main

env:
  PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
  PLAYWRIGHT_BROWSERS_PATH: /tmp/playwright
  CI: true

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install Dependencies
        run: bun install

      - name: Setup Docker
        run: bun run prepare:docker

      - name: Build Images
        run: docker compose build

      - name: Run Containers
        run: docker compose up -d

      - name: Install Playwright
        run: bunx playwright install --with-deps

      - name: Wait for Containers
        run: |
          until curl -s http://localhost:8000 > /dev/null; do
            sleep 1
          done

      - name: Run E2E Tests
        run: bun run --cwd ./tests/e2e test
        env:
          HOME: /root

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: ./tests/e2e/playwright-report/
          retention-days: 7

      - name: Stop Containers
        run: docker compose down
