name: shell

on:
  push:
    branches:
      - main
    paths:
      - 'apps/shell/**'
      - .github/workflows/shell.yml

env:
  DIR: apps/shell

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install
        run: bun install

      - name: Build Ui
        run: bun run build:ui

      - name: Lint
        run: bun run lint
        working-directory: ${{ env.DIR}}

      - name: Typecheck
        run: bun run typecheck
        working-directory: ${{ env.DIR}}

      - name: Test
        run: bun run test
        working-directory: ${{ env.DIR}}

      - name: Build
        run: bun run build
        working-directory: ${{ env.DIR}}
